let mock = [{
    id: 1,
    name: "Florida",
    severity: 72,
    status: "Damage done",
    problem: "Completely underwater",
  },
  {
    id: 2,
    name: "California",
    severity: 97,
    status: "Ongoing",
    problem: "Broken off and sinking into Pacific",
  },
  {
    id: 3,
    name: "Wyoming",
    severity: 0,
    status: "Unchanged",
    problem: "Wyoming has never existed",
},
{
    id: 4,
    name: "Australia",
    severity: 99,
    status: "Ongoing",
    problem: "Completely on fire, flooding, and severe storms simultaneously",
},
{
    id: 5,
    name: "Washington DC",
    severity: 3,
    status: "Unchanged",
    problem: "Zombie Outbreak",
},
{
    id: 6,
    name: "Russia",
    severity: 0,
    status: "Unchanged",
    problem: "Completely frozen",
},
{
    id: 7,
    name: "New York",
    severity: 53,
    status: "Ongoing",
    problem: "Every 3rd person being abducted by aliens",
},
{
    id: 8,
    name: "Japan",
    severity: 84,
    status: "Ongoing",
    problem: "Outbreak of contagious anime protagonist syndrome",
},
{
    id: 9,
    name: "UK",
    severity: 100,
    status: "Ongoing",
    problem: "Tea shortage",
},
{
    id: 10,
    name: "Ireland",
    severity: -3,
    status: "Ongoing",
    problem: "Border to UK closed",
},
{
    id: 11,
    name: "France",
    severity: 68,
    status: "Ongoing",
    problem: "Eiffel tower now a portal to Hell",
},
{
    id: 12,
    name: "Italy",
    severity: 94,
    status: "Ongoing",
    problem: "Pasta supply poisoned",
},
{
    id: 13,
    name: "Hawaii",
    severity: 53,
    status: "Ongoing",
    problem: "Radioactive sharks on attack",
},
{
    id: 14,
    name: "Canada",
    severity: 4,
    status: "Damage done",
    problem: "Someone got a little bit angry and was slightly rude",
},
]

export default mock;
